[GOV-410] API Gateway capabilities (Kong) - Observability
openMF/ph-ee-integration-test pull request #104
Opened 2023-08-09 17:26 UTC by ankita10r

## Description

Rate limiting implemetation for [GOV-410](https://mifosforge.jira.com/browse/GOV-410)

Updated the tag to :   @GOV-410 to disable this tc

 _(Ignore if these details are present on the associated JIRA ticket)_

SS:
<img width="1393" alt="Screenshot 2023-12-29 at 4 01 53 PM" src="https://github.com/openMF/ph-ee-integration-test/assets/92036361/ed6d6148-7662-446c-88d5-e2e20e7baf40">

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

[GOV-410]: https://mifosforge.jira.com/browse/GOV-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-16 12:03 UTC, avikganguly01 commented
@ankita10r : Even though CircleCI is passing this build, if I rerun the pipelines, it would fail. Each story's PRs have to be independent from other stories. I see you have already done a good job in keeping this PR independent from Danish's PR but the corresponding PR to G2P sandbox fyn SIT chart to enable Kong ingresses is not present so these TCs will fail without that PR triggerering first. Send env-labs PR, then retrigger this pipeline to get it mergeable and then retrigger env-labs pipeline to make the Env Labs PR mergeable.

2023-08-16 12:05 UTC, avikganguly01 requested changes
@ankita10r : Even though CircleCI is passing this build, if I rerun the pipelines, it would fail. Each story's PRs have to be independent from other stories. I see you have already done a good job in keeping this PR independent from Danish's PR but the corresponding PR to G2P sandbox fyn SIT chart to enable Kong ingresses is not present so these TCs will fail without that PR triggerering first. Send env-labs PR, then retrigger this pipeline to get it mergeable and then retrigger env-labs pipeline to make the Env Labs PR mergeable.

Your corresponding env-labs PR might break other TCs though once Kong ingress and rate limiting is enabled. So rate limiting has to be tested in a way so that it doesn't break other TCs due to rate limit.

2023-08-16 12:06 UTC, avikganguly01 commented on src/test/java/resources/kongSecurity.feature
> +  Scenario: API-KEY authentication test
@ankita10r : API Key (auth-n ) story shouldn't be part of this PR.

2023-12-29 10:50 UTC, fynmanoj approved these changes

2023-12-29 10:50 UTC, merged