[Phee 538] - Intergation test code refactoring
openMF/ph-ee-integration-test pull request #195
Opened 2024-01-23 07:25 UTC by dhruvsonagara

## Description

* PR title should have jira ticket enclosed in `[]`.<br>
  Format: ``` [jira_ticket] description```<br>
  ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Followed the PR title naming convention mentioned above.

- [ ] Acknowledge that we will not merge PRs that are not passing the checks ("green") - it is your (author's) responsibility to get a proposed PR to pass all the checks, not primarily the project's maintainers.

- [ ] The PR title should include a JIRA ticket

- [ ] Design-related bullet points or design document links related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or API documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

- [ ] Followed coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

FYI our guidelines for code reviews same as https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-01-24 05:50 UTC, fynmanoj requested changes

2024-01-24 05:50 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
> +    // protected static String batchId;
remove commented lines

2024-01-24 05:50 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeDef.java
rename class to ScenarioScopeState or ScenarioScopeCintext to match its purpose

2024-01-24 05:50 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
> +    ScenarioScopeDef scenarioScopeDef;
rename variable to scenarioScopeState or scenarioScopeCintext to match its purpose

2024-01-25 05:13 UTC, dhruvsonagara commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
> +    // protected static String batchId;
Done

2024-01-25 05:19 UTC, fynmanoj approved these changes

2024-01-25 05:21 UTC, merged