Payer
openMF/ph-ee-integration-test pull request #6
Opened 2023-02-10 08:05 UTC by dhruvsonagara

GSMA P2P API integration test added.

2023-02-10 08:40 UTC, danishjamal104 requested changes

2023-02-10 08:40 UTC, danishjamal104 commented on src/main/resources/application.yaml
> +  contactpoint: "https://channel.sandbox.fynarfin.io/"
extra slash will cause an issue when generating complete URL.

2023-02-10 08:40 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/GSMAStepdef.java
> +        gsmaTransaction = new GSMATransaction();
creating a DTO can be moved to a static functions. That static functions can be reused in this step definition.

2023-05-24 15:26 UTC, fynmanoj commented
@dhruvsonagara  please update this PR

2023-05-24 15:43 UTC, closed without merging