GOV-287.6 Added integration test for key-auth in hello-world service
openMF/ph-ee-integration-test pull request #68
Opened 2023-07-12 09:36 UTC by danishjamal104

Updates in this PR
1. Added integration test for kong key-auth in hello-world service.

JIRA -> [GOV-287](https://mifosforge.jira.com/browse/GOV-287)

2023-07-12 09:36 UTC, danishjamal104 commented
@fynmanoj @avikganguly01 Please review. Thanks :)

2023-07-12 11:50 UTC, danishjamal104 commented
@ankita10r you can refer this test case for enabling plugin in kong.

2023-07-20 15:22 UTC, fynmanoj commented
Please work on the checks

2023-08-18 10:59 UTC, fynmanoj approved these changes

2023-09-01 14:29 UTC, fynmanoj requested changes
requested clarification

2023-09-01 14:29 UTC, fynmanoj commented on src/main/resources/application.yaml
> +    host: "ph-ee-connector-bulk.paymenthub.80.svc"
why do we need the service here?

2023-09-02 10:03 UTC, merged