GOV-301: Batch Authorization integration test
openMF/ph-ee-integration-test pull request #90
Opened 2023-07-24 10:19 UTC by arkadasfynarfin

## Description

Jira link: [GOV-301](https://mifosforge.jira.com/browse/GOV-301)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-02 17:42 UTC, arkadasfynarfin commented
@fynmanoj Please review this PR.
CC: @avikganguly01

2023-08-16 13:46 UTC, avikganguly01 requested changes

2023-08-16 13:46 UTC, avikganguly01 commented on src/test/java/resources/batch.feature
> +    When I call the batch summary API with expected status of 200
@arkadasfynarfin : Isn't this an async API? Shouldn't it expect 202 response with an additional assert checking whether callback URL received the callback?

2023-08-17 17:41 UTC, avikganguly01 requested changes

2023-08-17 17:41 UTC, avikganguly01 commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +import org.mifos.integrationtest.config.MockPaymentSchemaConfig;
Please remove 4 unused imports.

2023-08-30 14:22 UTC, closed without merging