GOV-255 Added test case for te story
openMF/ph-ee-integration-test pull request #96
Opened 2023-08-01 07:11 UTC by danishjamal104

## Description

* Added text case as per design in [GOV-255](https://mifosforge.jira.com/browse/GOV-255)

```
Design
TC Design: Happy flow. Hit Batch Txn REST API without payer identifier and with the reg institution and program ID headers. Use the tenant <insert tenant name> for MinimalMockFundTransfer payment configuration.  Assert that completedAt timestamp is not null for this batch ID.
```

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above.

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-21 15:02 UTC, fynmanoj requested changes

2023-08-21 15:02 UTC, fynmanoj commented on src/test/java/resources/ph-ee-bulk-demo-13.csv
let's add the feature name to the file name of the data, it would be easy to identify them.

create a folder insider the resource folder and add all these files there.

2023-08-22 11:44 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +        assertThat(batchId).isNotEmpty();
that is already part of the scenario. Why to add it in this step?

2023-08-22 11:46 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +        assertThat(BaseStepDef.batchTransactionResponse).isNotNull();
check this step it is doing that. 
https://github.com/openMF/ph-ee-integration-test/blob/66cbc4b6b90fe46ef6cd0c276b34a84283a881e6/src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java#L126

2023-08-22 11:54 UTC, danishjamal104 commented on src/test/java/resources/batch.feature
> +    And I have the registeringInstituteId "123"
no need of configuration, since this is only testing if the feature is working or not at the bulkAPI level but not the budgetccount test.

2023-08-22 12:06 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +            e.printStackTrace();
done

2023-08-22 12:09 UTC, danishjamal104 commented on src/test/java/resources/ph-ee-bulk-demo-13.csv
done

2023-08-22 12:49 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +        assertThat(BaseStepDef.batchTransactionResponse).isNotNull();
I could not see specifically how the completed timestamp is not null and is checked, which is part of the design.

2023-08-23 09:46 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +        assertThat(BaseStepDef.batchTransactionResponse).isNotNull();
https://mifosforge.jira.com/browse/GOV-255?focusedCommentId=104168

2023-08-23 09:47 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> +        assertThat(BaseStepDef.batchTransactionResponse).isNotNull();
As per the comment listed above, resolving this conversation

2023-08-23 09:47 UTC, fynmanoj approved these changes

2023-08-23 09:54 UTC, merged